USBGuard QT
===========

== About

USBGuard is a software framework for implementing USB device authorization policies (what kind of USB devices are authorized) as well as method of use policies (how a USB device may interact with the system).
Simply put, it is a USB device whitelisting tool.

This repository contains the (basically unmodified) QT-GUI code from usbguard 0.7.4 with a simple buildscript.

== Documentation

¯\\_(ツ)_/¯

== Compilation & Installation

You'll need to install usbguard and qt5 dev-stuff first.

And then do:

    $ ./build.sh

== License

Copyright (C) 2015-2017 Red Hat, Inc.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
